---
title: "Conformal Prediction Intervals"
output: html_notebook
date: "2021-04-01"
---

$\hat y$

There is a [difference](https://robjhyndman.com/hyndsight/intervals/) between prediction and confidence intervals. 

# Prediction interval in general

- interval associated with a random variable that will be observed in future and the specific probability of the random variable being situated in this interval

Prediction interval for **new** response: 


Prediction interval always narrower due to "extra MSE" term. 

# Confidence interval in general

- frequentist concept concerned with the position of the non-random, but unknown parameter in relation to the interval ("containing the true parameter with some probability, given a large number of repeated samples")

Confidence interval for **mean** response: 






$SE_{fit}$ can approach zero 0 due to missing "extra MSE" term. 

# Bayesian credible interval

- interval associated with the posterior distribution of a parameter (parameters are random variables in Bayesian perspective). Similarity to prediction interval, but here the interval is concerned with a parameter value in contrast to the association with an observation when talking about prediction intervals. 



# Conformal prediction framework

* [Vovk et al. 2008](https://jmlr.org/papers/v9/shafer08a.html), more thorough treatment in ['Algorithmic  Learning in a Random World' by Vovk et al. (2005)](https://link.springer.com/book/10.1007/b106715). 



- Why? Validity of prediction intervals. The probability of excluding the correct target value is bounded by a predefined confidence level. It makes it possible to assess the uncertainty of each single prediction.


# Regression conformal prediction intervals

* [Johansson et al. 2014](https://link.springer.com/article/10.1007/s10994-014-5453-0
) 

## Inductive conformal prediction 


Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Cmd+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

